#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Summarize BWA/samtools alignment outputs.

Inputs:
- stats/*.idxstats.tsv generated by samtools idxstats
- stats/*.flagstat.txt generated by samtools flagstat

Outputs:
1) sample_mapping_summary.tsv
2) spikein_reads_matrix.tsv
3) spikein_expected_check.tsv
4) reference_mapped_reads_long.tsv
"""

import argparse
import csv
import re
from pathlib import Path


EXPECTED_SPIKEINS = {
    "F77":  list(range(1, 11)) + [11],
    "F153": list(range(1, 11)) + [12],
    "F88":  list(range(1, 11)) + [13],
    "F154": list(range(1, 11)) + [14],
    "F135": list(range(1, 11)) + [15],
    "F168": list(range(1, 11)) + [16],
    "F175": list(range(1, 11)) + [17],
    "F48":  list(range(1, 11)) + [18],
    "F49":  list(range(1, 11)) + [19],
    "F179": list(range(1, 11)) + [20],
}


def parse_flagstat(path):
    total = None
    mapped = None
    mapping_rate = None

    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()

            # Example:
            # 100 + 0 in total (QC-passed reads + QC-failed reads)
            if " in total " in line and total is None:
                m = re.match(r"^(\d+) \+ \d+ in total", line)
                if m:
                    total = int(m.group(1))

            # Example:
            # 95 + 0 mapped (95.00% : N/A)
            if " mapped (" in line and "primary" not in line and mapped is None:
                m = re.match(r"^(\d+) \+ \d+ mapped \(([\d\.]+)%", line)
                if m:
                    mapped = int(m.group(1))
                    mapping_rate = float(m.group(2))

    return total, mapped, mapping_rate


def infer_sample_id(filename):
    name = Path(filename).name
    for suffix in [".idxstats.tsv", ".flagstat.txt", ".sorted.bam", ".bam"]:
        if name.endswith(suffix):
            name = name[: -len(suffix)]
    return name


def identify_known_sample(sample_name):
    for sid in EXPECTED_SPIKEINS:
        # match F77 as a token in names such as xxx_F77_xxx or F77
        if re.search(rf"(^|[^A-Za-z0-9]){re.escape(sid)}([^A-Za-z0-9]|$)", sample_name):
            return sid
    return ""


def main():
    parser = argparse.ArgumentParser(description="Summarize target alignment statistics and spike-in detection.")
    parser.add_argument("--stats-dir", required=True, help="Directory containing *.idxstats.tsv and *.flagstat.txt")
    parser.add_argument("--out-dir", required=True, help="Output directory")
    parser.add_argument("--detect-threshold", type=int, default=5, help="Mapped reads threshold for detecting a spike-in")
    args = parser.parse_args()

    stats_dir = Path(args.stats_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    idx_files = sorted(stats_dir.glob("*.idxstats.tsv"))
    if not idx_files:
        raise SystemExit(f"No idxstats files found in {stats_dir}")

    long_rows = []
    spike_matrix = {}
    sample_gene_reads = {}
    sample_spike_reads = {}

    for idx in idx_files:
        sample = infer_sample_id(idx.name)
        spike_counts = {f"spikein_{i:02d}": 0 for i in range(1, 21)}
        gene_reads = 0
        total_spike_reads = 0

        with open(idx, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                parts = line.rstrip("\n").split("\t")
                if len(parts) < 4:
                    continue
                ref_id, length, mapped_reads, unmapped_reads = parts[:4]
                length = int(length)
                mapped_reads = int(mapped_reads)
                unmapped_reads = int(unmapped_reads)

                ref_type = "other"
                index = ""
                if ref_id.startswith("gene_"):
                    ref_type = "gene"
                    gene_reads += mapped_reads
                elif ref_id.startswith("spikein_"):
                    ref_type = "spikein"
                    index = ref_id.replace("spikein_", "")
                    spike_counts[ref_id] = mapped_reads
                    total_spike_reads += mapped_reads

                long_rows.append([sample, ref_id, ref_type, index, length, mapped_reads, unmapped_reads])

        spike_matrix[sample] = spike_counts
        sample_gene_reads[sample] = gene_reads
        sample_spike_reads[sample] = total_spike_reads

    # mapping summary from flagstats
    mapping_rows = []
    for sample in sorted(spike_matrix):
        flag = stats_dir / f"{sample}.flagstat.txt"
        total, mapped, rate = (None, None, None)
        if flag.exists():
            total, mapped, rate = parse_flagstat(flag)
        mapping_rows.append([
            sample,
            identify_known_sample(sample),
            total if total is not None else "",
            mapped if mapped is not None else "",
            rate if rate is not None else "",
            sample_gene_reads.get(sample, 0),
            sample_spike_reads.get(sample, 0),
        ])

    with open(out_dir / "sample_mapping_summary.tsv", "w", encoding="utf-8", newline="") as out:
        writer = csv.writer(out, delimiter="\t")
        writer.writerow([
            "sample", "known_sample_id", "total_reads_from_flagstat",
            "mapped_reads_from_flagstat", "mapping_rate_percent",
            "mapped_reads_to_gene_refs", "mapped_reads_to_spikeins"
        ])
        writer.writerows(mapping_rows)

    with open(out_dir / "spikein_reads_matrix.tsv", "w", encoding="utf-8", newline="") as out:
        writer = csv.writer(out, delimiter="\t")
        header = ["sample", "known_sample_id"] + [f"spikein_{i:02d}" for i in range(1, 21)]
        writer.writerow(header)
        for sample in sorted(spike_matrix):
            row = [sample, identify_known_sample(sample)]
            row.extend(spike_matrix[sample].get(f"spikein_{i:02d}", 0) for i in range(1, 21))
            writer.writerow(row)

    with open(out_dir / "spikein_expected_check.tsv", "w", encoding="utf-8", newline="") as out:
        writer = csv.writer(out, delimiter="\t")
        writer.writerow([
            "sample", "known_sample_id", "expected_spikeins",
            "detected_spikeins", "missing_expected_spikeins",
            "unexpected_detected_spikeins", "detect_threshold_reads"
        ])

        for sample in sorted(spike_matrix):
            sid = identify_known_sample(sample)
            expected = set(EXPECTED_SPIKEINS.get(sid, []))
            detected = {
                int(ref.replace("spikein_", ""))
                for ref, count in spike_matrix[sample].items()
                if count >= args.detect_threshold
            }

            missing = sorted(expected - detected) if expected else []
            unexpected = sorted(detected - expected) if expected else sorted(detected)

            writer.writerow([
                sample,
                sid,
                ",".join(str(x) for x in sorted(expected)),
                ",".join(str(x) for x in sorted(detected)),
                ",".join(str(x) for x in missing),
                ",".join(str(x) for x in unexpected),
                args.detect_threshold,
            ])

    with open(out_dir / "reference_mapped_reads_long.tsv", "w", encoding="utf-8", newline="") as out:
        writer = csv.writer(out, delimiter="\t")
        writer.writerow(["sample", "reference_id", "reference_type", "spikein_index", "length_bp", "mapped_reads", "unmapped_reads"])
        writer.writerows(long_rows)

    print(f"Processed {len(idx_files)} samples.")
    print(f"Wrote outputs to {out_dir}")
    print("Key files:")
    print(f"- {out_dir / 'sample_mapping_summary.tsv'}")
    print(f"- {out_dir / 'spikein_reads_matrix.tsv'}")
    print(f"- {out_dir / 'spikein_expected_check.tsv'}")
    print(f"- {out_dir / 'reference_mapped_reads_long.tsv'}")


if __name__ == "__main__":
    main()
